name = "streamflix-tv-backend"
main = "src/index.js"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]

[vars]
TMDB_BASE_URL = "https://api.themoviedb.org/3"
ANIKOTO_API_URL = "https://anikotoapi.site"
JIKAN_API_URL = "https://api.jikan.moe/v4"
MEGAPLAY_EMBED_URL = "https://megaplay.buzz"
NODE_ENV = "production"

[dev]
port = 8787
